apiVersion: batch/v1
kind: Job
metadata:
  name: eks-irsa-s3
spec:
  template:
    metadata:
      labels:
        app: eks-irsa-s3
    spec:
      serviceAccountName: eks-irsa
      containers:
      - name: eks-irsa-s3
        image: amazon/aws-cli:latest
        args: ["s3", "ls"]
      restartPolicy: Never
