apiVersion: batch/v1
kind: Job
metadata:
  name: eks-irsa-ec2
spec:
  template:
    metadata:
      labels:
        app: eks-irsa-ec2
    spec:
      serviceAccountName: eks-irsa
      containers:
      - name: eks-irsa-s3
        image: amazon/aws-cli:latest
        args: ["ec2", "describe-instances", "--region", "ap-northeast-1"]
      restartPolicy: Never
  backoffLimit: 0

